- name: Installing and Configuring Cataloge
  hosts: catalogue
  become: yes
  tasks:
    - name: Setting up nodejs repos from script provided by vendor.
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

    - name: Installing NodeJs
      ansible.builtin.yum:
        name: nodejs
        state: installed

    - name: verify and create roboshop user if doesnt exist already
      ansible.builtin.command: id roboshop
      register: exitstatus
      ignore_errors: true
    
      when: exitstatus.rc != 0
    - name: Create user
      ansible.builtin.user:
        name: roboshop

    - name: verify and create app directory if doesnt exist already
      ansible.builtin.stat:
        path: /app
        register: direxiststatus

    when: direxiststatus.stat.exists == false
    - name: create directory
      ansible.builtin.file: 
        path: /app
        state: directory

    - name: Download the code form URL
      ansible.builtin.get-url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp  

    - name: unzip downloaded file into app directory
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: Downlaod Dependencies
      ansible.builtin.command: npm install
        args:
          chdir: /app
            
    - name: Copy Catalogue Service
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: Load the service
      ansible.builtin.systemd:
        daemon-reload: true
    
    - name: Enable and Start the Service
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: true

    - name: Copying mongo repo file
      ansible.builtin.copy:
        src:  mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Installing mongodb client
      ansible.builtin.yum:
        name: mongodb-org-shell 
        state: Installed

    - name: Load Schema
      ansible.builtin.command: mongo --host mongodb.robokart.online < /app/schema/catalogue.js
         
    - name: Restart the Service
      ansible.builtin.service:
        name: catalogue
        state: restarted
        enabled: true
      