- name: Installing and Configuring rabbitmq
  hosts: rabbitmq
  become: yes
  tasks:
    - name: Configuring Yum repos from script provided by vendor
      ansible.builtin.shell: "{{ item }}"
      loop:
        - curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
        - curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash
    
    - name: Install RabbitMQ
      ansible.builtin.yum:
        name: rabbitmq-server 
        state: present

    - name: Enable and Start rabbitmq
      ansible.builtin.service:
        name: rabbitmq-server 
        state: started
        enabled: true
    
    - name: Verify and Add user roboshop if doesnot exist
      ansible.builtin.command: id roboshop
      register: exitstaus

    - when: existstaus.rc != 0
      name: add user
      ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123

    - name: set permissions
      ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"



