- name: Installing and Configuring redis database
  hosts: redis
  become: yes
  tasks:
    - name: Installing redis from rpm
      ansible.builtin.yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: present
        disable_gpg_check: true
    - name: enable redis 6.2 module from package streams
      ansible.builtin.command: yum module enable redis:remi-6.2 -y

    - name: Installing redis
      ansible.builtin.yum:
        name: redis
        state: installed

    - name: Replace 127.0.0.1 to 0.0.0.0 in /etc/redis.conf 
      ansible.builtin.replace:
        path: /etc/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Replace 127.0.0.1 to 0.0.0.0 in /etc/redis/redis.conf
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'  

    - name: Enable & Start Redis
      ansible.builtin.service:
        name: redis
        state: started
        enabled: yes         
            