- name: Installation and configuration of nginx server
  hosts: localhost
  become: yes
  tasks:
    - name: Installing nginx server
      ansible.builtin.yum:
        name: nginx
        state: installed
    
    - name: Enable & Start nginx server
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name:       