- name: Installation and configuration of nginx server
  hosts: web
  become: yes
  tasks:
    - name: Installing nginx server
      ansible.builtin.yum:
        name: nginx
        state: installed
      
    - name: Enable & Start nginx server
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Removing default content that web is serving
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Create HTML folder
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Download the frontend content
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/web.zip
        dest: /tmp/web.zip 

    - name: unzip frontend conent to html folder
      ansible.builtin.unarchive:
        src: /tmp/web.zip
        dest: /usr/share/nginx/html
        remote_src: yes        

    
                 


         