- name: Installation and configuration of nginx server
  hosts: web
  become: yes
  tasks:
    - name: Installing nginx server
      ansible.builtin.yum:
        name: nginx
        state: installed
      
    - name: Enable & Start nginx server
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Removing default content that web is serving
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent


         